[pack]
# The name of your pack to display in the scripts welcome message
name = "the LAMZPack"
# Url to your modpacks data. Must be a zip containing a mods folder and config folder in its root. Must be direct DL link.
url = ""
# The semantic version of your pack. Leave this default if your pack is brand new
version = "1.0.0"

[upload]
# Public IP address for the system your pack is hosted on
host = "xxx.xxx.xxx.xxx"
# SSH-FTP (SFTP) port (must be forwarded!) on the host system you pack lives on. Usually default unless you changed it.
port = 22
# Username and password for the user account you are using SSH to access. 
username = ""
password = ""
# Path to the folder you want your modpack version folders to live. This is usually the same as the path in your URL setting above.
# I would recommend using apache2 to host it on /var/www/<something>. This program does not work with dropbox or anything. Only something accessable via SFTP.
filepath = ""
